server:
  port: 8888
spring:
  application:
    name: erudio-config-server
  #  profiles:
  #    active:
  #      - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ALEXFARW/erudio-config-server
          #username (poderia passar se o reposit fosse privado)
          #password
          default-label: main
            - 'greeting-service*'